name: Apply Label to New Issue based on its Title

on:
  issue_comment:
    types:
      - opened

jobs:
  apply-label-to-new-issue-based-on-title:
    name: Apply Label to New Issue based on its Title
    runs-on: ubuntu-latest
    steps:
      # follows semantic versioning. Lock to different version: v1, v1.5, v1.5.0 or use a commit hash.
      - uses: leovipin1/label-issue-pr-based-on-content@main
        with:
          github-token: ${{ secrets.LIFE_ENGINE_DESIGNER_SECRET }} # optional, default to '${{ github.token }}'  
          config-path: .github/issue-title-based-labeler.yml # optional, default to '.github/labeler.yml'
