name: Add Label to Closed Issue/PR

on:
  issues:
    types: 
      - closed
  pull_request:
    types: 
      - closed

jobs:
  add-labels-to-closed-issue-pr:
    name: Add Label to Closed Issue/PR
    runs-on: ubuntu-latest
    steps:
      - uses: leovipin1/add-label-to-issue-pr@master
        with:
          add-labels: 'Status: Closed'
          remove-labels: 'Status: Developing'
          repo-token: ${{ secrets.LIFE_ENGINE_DESIGNER_SECRET }}
