name: Add Label to Reopened Issue/PR

on:
  issues:
    types:
      - reopened
  pull_request:
    types: 
      - reopened

jobs:
  add-label-to-reopened-issue-pr:
    name: Add Label to Reopened Issue/PR
    runs-on: ubuntu-latest
    steps:
      - uses: leovipin1/add-label-to-issue-pr@master
        with:
          add-labels: 'Status: Reopened, Status: Developing'
          remove-labels: 'Status: Closed'
          repo-token: ${{ secrets.LIFE_ENGINE_DESIGNER_SECRET }}