name: 'Support Requests'

on:
  issues:
    types: labeled
  pull_request:
    types: labeled

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/support-requests@main
        with:
          github-token: ${{ secrets.LIFE_ENGINE_DESIGNER_SECRET }}
          support-label: 'rejected'
          issue-comment: >
            :wave: @{issue-author}, we use the issue tracker exclusively
            for bug reports and feature requests. However, this issue appears
            to be a support request. Please use our support channels
            to get help with the project.
          close-issue: true
          lock-issue: true
          issue-lock-reason: 'resolved'
